# Generated by Django 4.0.3 on 2022-06-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='salesprice',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
