# Generated by Django 4.0.3 on 2022-06-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_technician_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vip',
            field=models.BooleanField(null=True),
        ),
    ]
