# Generated by Django 4.0.3 on 2022-06-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_appointment_date_time_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vip',
        ),
    ]
